CREATE TABLE IF NOT EXISTS submissions (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(20) NOT NULL,
  class_name VARCHAR(50),
  created_at TIMESTAMP DEFAULT NOW(),
  submitted_at TIMESTAMP,
  is_complete BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS responses (
  id SERIAL PRIMARY KEY,
  submission_id INTEGER REFERENCES submissions(id),
  child_slot VARCHAR(10) NOT NULL,
  child_name VARCHAR(50),
  child_age INTEGER,
  q1 SMALLINT, q2 SMALLINT, q3 SMALLINT, q4 SMALLINT, q5 SMALLINT,
  q6 SMALLINT, q7 SMALLINT, q8 SMALLINT, q9 SMALLINT, q10 SMALLINT,
  q11 SMALLINT, q12 SMALLINT, q13 SMALLINT, q14 SMALLINT, q15 SMALLINT,
  q16 SMALLINT, q17 SMALLINT, q18 SMALLINT, q19 SMALLINT, q20 SMALLINT,
  q21 SMALLINT, q22 SMALLINT, q23 SMALLINT, q24 SMALLINT, q25 SMALLINT,
  q26 SMALLINT,
  updated_at TIMESTAMP DEFAULT NOW()
);
